In [12]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8 #size of our tensor
batch_size = 4

cuda


In [13]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [14]:
#encoding-decoding all our chars in the text i.e. tokenization
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}

encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l : ''.join([int_to_string[i]] for i in l)

data = torch.tensor(encode(text), dtype = torch.long)

print(data[:100])

tensor([79,  0, 32, 72,  5, 71,  1, 66, 67,  1, 73, 71, 57, 22,  1, 66, 67,  1,
        73, 71, 57,  1, 53, 72,  1, 53, 64, 64, 10,  1, 43, 60, 57,  1, 55, 60,
        61, 64, 56, 70, 57, 66,  1, 75, 67, 66,  5, 72,  1, 64, 57, 72,  1, 65,
        57,  1, 71, 72, 67, 68,  1, 72, 57, 64, 64, 61, 66, 59,  1, 72, 53, 64,
        57, 71,  0, 67, 58,  1, 72, 60, 57,  1, 35, 53, 66, 56,  1, 67, 58,  1,
        38, 78, 10,  1, 32,  1, 63, 66, 67, 75])


In [19]:
n = int(0.8 * len(data))

train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split=='train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix] )
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    #x, y = x.to(device), y.to(device) -- Found GPU0 GeForce GTX 760 which is of cuda capability 3.0.
    return x,y

x,y = get_batch('train')
print('inputs: ')
print(x)

print('targets: ')
print(y)

tensor([149970,  84232,  78821,  98514])
inputs: 
tensor([[56, 70, 53, 59, 67, 66, 57, 72],
        [70,  1, 57, 64, 57, 74, 53, 72],
        [59, 64, 53, 71, 71,  1, 70, 67],
        [73, 57,  8,  3,  1, 60, 57,  1]])
targets: 
tensor([[70, 53, 59, 67, 66, 57, 72, 72],
        [ 1, 57, 64, 57, 74, 53, 72, 57],
        [64, 53, 71, 71,  1, 70, 67, 55],
        [57,  8,  3,  1, 60, 57,  1, 70]])


In [16]:


class BigramLanguageModel(nn.module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, index, targets):
        logits = self.token_embedding_table(index)
        return logits


when input is  tensor([79]) the targe is tensor(0)
when input is  tensor([79,  0]) the targe is tensor(32)
when input is  tensor([79,  0, 32]) the targe is tensor(72)
when input is  tensor([79,  0, 32, 72]) the targe is tensor(5)
when input is  tensor([79,  0, 32, 72,  5]) the targe is tensor(71)
when input is  tensor([79,  0, 32, 72,  5, 71]) the targe is tensor(1)
when input is  tensor([79,  0, 32, 72,  5, 71,  1]) the targe is tensor(66)
when input is  tensor([79,  0, 32, 72,  5, 71,  1, 66]) the targe is tensor(67)
