In [2]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [7]:
#define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
#10% or 0.1 => 0,90% or 0.9 => each probability 
#draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 0, 0, 1, 1, 1, 1, 1])


In [9]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0) #concatinate tensors , willl be useful while generating text
out

tensor([1, 2, 3, 4, 5])

In [10]:
out = torch.triu(torch.ones(4,4))
out

tensor([[1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.]])

In [12]:
masked = torch.zeros(4,4).masked_fill(torch.tril(torch.ones(4,4))==0, float('-inf'))
masked

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [13]:
tensor1 = torch.tensor([1,2,4])
tensor2 = torch.tensor([3,4,5])

stack = torch.stack([tensor1,tensor2])
stack

tensor([[1, 2, 4],
        [3, 4, 5]])

In [17]:
import torch.nn as nn #nn stands for neural networks
sample = torch.tensor([10.0, 10.0, 10.0]) 
linear = nn.Linear(3, 3, bias=False) #creatiang a linear nn layer with no bias

print(linear(sample))

tensor([-6.0190, -9.4326,  2.6168], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_outp = F.softmax(tensor1, dim=0); #applying softmax transformation to a tensor

print(softmax_outp)

tensor([0.0900, 0.2447, 0.6652])


In [24]:
#embedding layer 
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])
embedded_output = embedding(input_indices)

#the out put will be a tensor of shape (4, 100) , where 4 is the number of inputs
#and 100 is the dimensionality of the embedding vectors

print(embedded_output.shape)

torch.Size([4, 100])
