In [1]:
import torch

In [3]:
randint = torch.randint(-100, 100, (6, ))
randint

tensor([-26,  29, -71, -19, -22, -44])

In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
empties = torch.empty(2,3)
empties #either very large or very small nos

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
linspace = torch.linspace(3, 10, steps=5) # going from 3 to 10 in 5 equal steps
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
logspace = torch.logspace(start=-10, end=10, steps=5);
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])